site_name: Documentation
site_description: |
  The documentation for NOMAD v1.
site_author: The NOMAD Authors
nav:
  - Home: index.md
  - Tutorial: tutorial.md
  - How-to guides:
    - Data Management:
      - How to upload/publish data: data/upload.md
      - How to use ELNs: data/eln.md
      - How to explore data: data/explore.md
      - How to use NORTH: data/north.md
    - Schemas:
      - How to write a schema: schemas/basics.md
      - How to define ELNs: schemas/elns.md
      - How to use base sections: schemas/base_sections.md
      - How to define tabular data: schemas/tabular.md
      - How to define workflows: schemas/workflows.md
      - How to reference hdf5: schemas/hdf5.md
    - Programming interfaces:
      - How to use the API: apis/api.md
      - How to install nomad-lab: apis/pythonlib.md
      - How to access processed data: apis/archive_query.md
      - How to run a parser: apis/local_parsers.md
    - Plugins:
      - How to develop, publish, and install plugins: plugins/plugins.md
      - How to write schema plugins: plugins/schemas.md
      - How to write parser plugins: plugins/parsers.md
    - Development:
      - How to get started: develop/setup.md
      - How to navigate the code: develop/code.md
      - How to contribute: develop/contrib.md
      - Code guidelines: develop/guides.md
      - How to extend the search: develop/search.md
      - How to write a parser: develop/parsers.md
      - How to write a normalizer: develop/normalizers.md
    - Oasis:
      - How to install an Oasis: oasis/install.md
      - How to customize an Oasis: oasis/customize.md
      - How to migrate Oasis versions: oasis/migrate.md
      - Administrative tasks: oasis/admin.md
  - Learn:
    - From files to data: learn/basics.md
    - Structured data: learn/data.md
    - Architecture: learn/architecture.md
    - Why you need an Oasis: learn/oasis.md
  - Reference:
    - reference/config.md
    - reference/annotations.md
    - reference/cli.md
    - reference/plugins.md
    - reference/parsers.md
    - reference/glossary.md
theme:
  name: material
  palette:
    primary: '#2A4CDF'
    accent: '#008A67'
  font:
    text: 'Titillium Web'
  logo: assets/nomad-logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
  custom_dir: docs/theme
# repo_url: https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: True
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - mkdocs-click
  - pymdownx.extra
extra:
  generator: false
  homepage: https://nomad-lab.eu
use_directory_urls: false
plugins:
    - search
    - macros:
        module_name: nomad/mkdocs
    - redirects:
        redirect_maps:
          'plugins.md': 'plugins/plugins.md'
          'pythonlib.md': 'apis/pythonlib.md'
          'oasis.md': 'oasis/install.md'
          'develop/gitlab.md': 'develop/contrib.md'
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js