version:
  label: process
  isBeta: true
  usesBetaData: false
  officialUrl: "https://nomad-lab.eu/prod/v1/gui"

image:
  tag: "process"
  pullPolicy: "Always"

proxy:
  nodePort: 30020
  nodeIP: "130.183.207.81"
  external:
    host: "nomad-lab.eu"
    path: "/prod/v1/process"

gui:
  debug: true
  matomoEnabled: false
  matomoSiteId: 2
  encyclopediaBase: "https://nomad-lab.eu/prod/rae/encyclopedia/#"
  aitoolkitEnabled: false

app:
  replicas: 1
  worker: 1
  nomadNodeType: "public"

celery:
  timeout: 7200

worker:
  replicas: 2
  routing: "worker"
  processes: 8
  memrequest: 256
  memlimit: 488
  nomadNodeType: "worker"

process:
  rfc3161_skip_published: true

elastic:
  host: elasticsearch.elasticsearch-7.svc.cluster.local
  port: 9200
  dbname: nomad_prod_v1.2
  secret: nomad-elastic

mongo:
  host: mongodb://mongodb-0.mongo.mongodb.svc.cluster.local,mongodb-1.mongo.mongodb.svc.cluster.local,mongodb-2.mongo.mongodb.svc.cluster.local/?replicaSet=rs0
  secret: nomad-mongo

logstash:
  host: logstash.elk.svc.cluster.local

dbname: nomad_prod_v1

uploadurl: "https://nomad-lab.eu/prod/v1/process/api/uploads"

client:
  passwordSecret: "nomad-keycloak-password"

keycloak:
  serverUrl: "https://nomad-lab.eu/fairdi/keycloak/auth/"
  serverExternalUrl: "https://nomad-lab.eu/fairdi/keycloak/auth/"
  passwordSecret: "nomad-keycloak-password"
  realmName: "fairdi_nomad_prod"
  clientId: "nomad_public"
  admin_user_id: "82efac55-6187-408c-8027-b98580c0e1c5"

volumes:
  prefixSize: 1
  public: /nomad/fairdi/prod/fs/public
  staging: /scratch/fairdi/prod/fs/staging
  north_home: /nomad/fairdi/prod/fs/north/users
  tmp: /nomad/fairdi/prod/fs/tmp
  nomad: /nomad
  archiveVersionSuffix: v1.2

mail:
  enabled: false
  host: "mailrelay.mpcdf.mpg.de"
  port: 25
  from: "support@nomad-lab.eu"

datacite:
  secret: "nomad-datacite"
  enabled: false

north:
  enabled: false

archive:
  use_new_writer: true
