nomad:
  config:
    version:
      label: beta/staging
      isBeta: true
      usesBetaData: false
      officialUrl: "https://nomad-lab.eu/prod/v1/gui"

    proxy:
      external:
        path: "/prod/v1/util"

    gui:
      debug: true

    dbname: nomad_prod_v1

    uploadurl: "https://cloud.nomad-lab.eu/prod/v1/util/api/uploads"

    mail:
      enabled: false

    datacite:
      enabled: false

    north:
      enabled: false

  image:
    tag: "prod"

  ingress:
    hosts:
      - host: nomad-lab.eu
        paths:
          - path: /prod/v1/util/
            pathType: ImplementationSpecific

  app:
    replicaCount: 1

  worker:
    replicaCount: 1
    processes: 4
    resources:
      limits:
        memory: "256Gi"
      requests:
        memory: "8Gi"
